/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrmGUI;

/**
 *
 * @author equipo 1
 */
public class frmCrear extends javax.swing.JFrame {

    String FA = "Fondo de apuesta: ";
    String MA = "Minimo de apuesta: ";
    int fondo_apuesta;
    int minimo_apuesta;

    /**
     * Creates new form frmCrear
     */
    public frmCrear() {
        initComponents();
        setLocationRelativeTo(null);

        fondo_apuesta = 10;
        minimo_apuesta = 1;
        lblFondoApuesta.setText(FA + fondo_apuesta);
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearPartida = new javax.swing.JLabel();
        pnlCrearPartida = new javax.swing.JPanel();
        lblFondoApuesta = new javax.swing.JLabel();
        lblMinimoApuesta = new javax.swing.JLabel();
        btnFA = new javax.swing.JPanel();
        btnFAMas1 = new javax.swing.JButton();
        btnFAMas10 = new javax.swing.JButton();
        btnFAMas25 = new javax.swing.JButton();
        btnFAMenos1 = new javax.swing.JButton();
        btnFAMenos10 = new javax.swing.JButton();
        btnFAMenos25 = new javax.swing.JButton();
        btnMA = new javax.swing.JPanel();
        btnMAMas1 = new javax.swing.JButton();
        btnMAMas10 = new javax.swing.JButton();
        btnMAMas25 = new javax.swing.JButton();
        btnMAMenos1 = new javax.swing.JButton();
        btnMAMenos10 = new javax.swing.JButton();
        btnMAMenos25 = new javax.swing.JButton();
        lblNumJugadores = new javax.swing.JLabel();
        cbxNumJugadores = new javax.swing.JComboBox<>();
        lblNumFichas = new javax.swing.JLabel();
        cbxNumFichas = new javax.swing.JComboBox<>();
        lblCasillasAspa = new javax.swing.JLabel();
        cbxCasillasAspa = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCrearPartida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCrearPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrearPartida.setText("Crear Partida");

        lblFondoApuesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFondoApuesta.setText("Fondo de apuesta:");

        lblMinimoApuesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMinimoApuesta.setText("Minimo de apuesta:");

        btnFAMas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMas1.setText("+1");
        btnFAMas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMas1ActionPerformed(evt);
            }
        });

        btnFAMas10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMas10.setText("+10");
        btnFAMas10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMas10ActionPerformed(evt);
            }
        });

        btnFAMas25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMas25.setText("+25");
        btnFAMas25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMas25ActionPerformed(evt);
            }
        });

        btnFAMenos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMenos1.setText("-1");
        btnFAMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMenos1ActionPerformed(evt);
            }
        });

        btnFAMenos10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMenos10.setText("-10");
        btnFAMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMenos10ActionPerformed(evt);
            }
        });

        btnFAMenos25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFAMenos25.setText("-25");
        btnFAMenos25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAMenos25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnFALayout = new javax.swing.GroupLayout(btnFA);
        btnFA.setLayout(btnFALayout);
        btnFALayout.setHorizontalGroup(
            btnFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFALayout.createSequentialGroup()
                .addComponent(btnFAMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFAMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFAMenos25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnFALayout.createSequentialGroup()
                .addComponent(btnFAMas1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFAMas10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFAMas25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFALayout.setVerticalGroup(
            btnFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFALayout.createSequentialGroup()
                .addGroup(btnFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFAMas1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFAMas10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFAMas25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(btnFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFAMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFAMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFAMenos25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnMAMas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMas1.setText("+1");
        btnMAMas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMas1ActionPerformed(evt);
            }
        });

        btnMAMas10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMas10.setText("+10");
        btnMAMas10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMas10ActionPerformed(evt);
            }
        });

        btnMAMas25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMas25.setText("+25");
        btnMAMas25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMas25ActionPerformed(evt);
            }
        });

        btnMAMenos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMenos1.setText("-1");
        btnMAMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMenos1ActionPerformed(evt);
            }
        });

        btnMAMenos10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMenos10.setText("-10");
        btnMAMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMenos10ActionPerformed(evt);
            }
        });

        btnMAMenos25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMAMenos25.setText("-25");
        btnMAMenos25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAMenos25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnMALayout = new javax.swing.GroupLayout(btnMA);
        btnMA.setLayout(btnMALayout);
        btnMALayout.setHorizontalGroup(
            btnMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMALayout.createSequentialGroup()
                .addComponent(btnMAMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMAMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMAMenos25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnMALayout.createSequentialGroup()
                .addComponent(btnMAMas1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMAMas10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMAMas25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMALayout.setVerticalGroup(
            btnMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMALayout.createSequentialGroup()
                .addGroup(btnMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMAMas1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMAMas10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMAMas25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(btnMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMAMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAMenos25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblNumJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumJugadores.setText("Num. de jugadores:");

        cbxNumJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxNumJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2", "3", "4" }));

        lblNumFichas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumFichas.setText("Num. de fichas:");

        cbxNumFichas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxNumFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2", "3", "4", "5", "6" }));

        lblCasillasAspa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCasillasAspa.setText("Num. de casillas por aspa:");

        cbxCasillasAspa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxCasillasAspa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "8", "9", "10", "11", "12", "13", "14" }));

        javax.swing.GroupLayout pnlCrearPartidaLayout = new javax.swing.GroupLayout(pnlCrearPartida);
        pnlCrearPartida.setLayout(pnlCrearPartidaLayout);
        pnlCrearPartidaLayout.setHorizontalGroup(
            pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearPartidaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFondoApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCasillasAspa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimoApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCrearPartidaLayout.createSequentialGroup()
                        .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNumFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCasillasAspa, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlCrearPartidaLayout.setVerticalGroup(
            pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearPartidaLayout.createSequentialGroup()
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNumFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasillasAspa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCasillasAspa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCrearPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblCrearPartida)
                .addGap(51, 51, 51)
                .addComponent(pnlCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFAMas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMas1ActionPerformed
        if (fondo_apuesta + 1 <= 1000) {
            fondo_apuesta += 1;
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
    }//GEN-LAST:event_btnFAMas1ActionPerformed

    private void btnFAMas10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMas10ActionPerformed
        if (fondo_apuesta + 10 <= 1000) {
            fondo_apuesta += 10;
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
    }//GEN-LAST:event_btnFAMas10ActionPerformed

    private void btnFAMas25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMas25ActionPerformed
        if (fondo_apuesta + 25 <= 1000) {
            fondo_apuesta += 25;
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
    }//GEN-LAST:event_btnFAMas25ActionPerformed

    private void btnFAMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMenos1ActionPerformed
        if (fondo_apuesta - 1 >= 10) {
            fondo_apuesta -= 1;
            if (minimo_apuesta > fondo_apuesta / 10) {
                minimo_apuesta = fondo_apuesta / 10;
            }
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnFAMenos1ActionPerformed

    private void btnFAMenos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMenos10ActionPerformed
        if (fondo_apuesta - 10 >= 10) {
            fondo_apuesta -= 10;
            if (minimo_apuesta > fondo_apuesta / 10) {
                minimo_apuesta = fondo_apuesta / 10;
            }
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnFAMenos10ActionPerformed

    private void btnFAMenos25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAMenos25ActionPerformed
        if (fondo_apuesta - 25 >= 10) {
            fondo_apuesta -= 25;
            if (minimo_apuesta > fondo_apuesta / 10) {
                minimo_apuesta = fondo_apuesta / 10;
            }
        }
        lblFondoApuesta.setText(FA + fondo_apuesta);
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnFAMenos25ActionPerformed

    private void btnMAMas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMas1ActionPerformed
        if (minimo_apuesta + 1 <= fondo_apuesta / 10) {
            minimo_apuesta += 1;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnMAMas1ActionPerformed

    private void btnMAMas10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMas10ActionPerformed
        if (minimo_apuesta + 10 <= fondo_apuesta / 10) {
            minimo_apuesta += 10;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnMAMas10ActionPerformed

    private void btnMAMas25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMas25ActionPerformed
        if (minimo_apuesta + 25 <= fondo_apuesta / 10) {
            minimo_apuesta += 25;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);
    }//GEN-LAST:event_btnMAMas25ActionPerformed

    private void btnMAMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMenos1ActionPerformed
        if (minimo_apuesta - 1 > 0) {
            minimo_apuesta -= 1;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);    }//GEN-LAST:event_btnMAMenos1ActionPerformed

    private void btnMAMenos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMenos10ActionPerformed
        if (minimo_apuesta - 10 > 0) {
            minimo_apuesta -= 10;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);    }//GEN-LAST:event_btnMAMenos10ActionPerformed

    private void btnMAMenos25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAMenos25ActionPerformed
        if (minimo_apuesta - 25 > 0) {
            minimo_apuesta -= 25;
        }
        lblMinimoApuesta.setText(MA + minimo_apuesta);    }//GEN-LAST:event_btnMAMenos25ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        int fondoApuesta = this.fondo_apuesta;
        int minimoApuesta = this.minimo_apuesta;
        int numeroJugadores = cbxNumJugadores.getSelectedIndex() + 1;
        int numeroFichas = cbxNumFichas.getSelectedIndex() + 1;
        int numeroCasillas = cbxCasillasAspa.getSelectedIndex() + 7;

        if (numeroJugadores >= 2 && numeroFichas >= 2 && numeroCasillas >= 8) {
            int[] array = new int[]{
                fondoApuesta, minimoApuesta, numeroJugadores, numeroFichas, numeroCasillas
            };
            frmTablero tablero = new frmTablero(array);
            new frmLobby(tablero).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel btnFA;
    private javax.swing.JButton btnFAMas1;
    private javax.swing.JButton btnFAMas10;
    private javax.swing.JButton btnFAMas25;
    private javax.swing.JButton btnFAMenos1;
    private javax.swing.JButton btnFAMenos10;
    private javax.swing.JButton btnFAMenos25;
    private javax.swing.JPanel btnMA;
    private javax.swing.JButton btnMAMas1;
    private javax.swing.JButton btnMAMas10;
    private javax.swing.JButton btnMAMas25;
    private javax.swing.JButton btnMAMenos1;
    private javax.swing.JButton btnMAMenos10;
    private javax.swing.JButton btnMAMenos25;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxCasillasAspa;
    private javax.swing.JComboBox<String> cbxNumFichas;
    private javax.swing.JComboBox<String> cbxNumJugadores;
    private javax.swing.JLabel lblCasillasAspa;
    private javax.swing.JLabel lblCrearPartida;
    private javax.swing.JLabel lblFondoApuesta;
    private javax.swing.JLabel lblMinimoApuesta;
    private javax.swing.JLabel lblNumFichas;
    private javax.swing.JLabel lblNumJugadores;
    private javax.swing.JPanel pnlCrearPartida;
    // End of variables declaration//GEN-END:variables
}
