/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.server.patolli;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Choche
 */
public class frmLobby extends javax.swing.JFrame {

    int jugadores = 0;
    private int[] perfiles = new int[] {0, 0, 0, 0};
    private final ImageIcon[] fotos = new ImageIcon[] {
        new ImageIcon("src/main/java/com/server/patolli/img/perfil1.png"),
        new ImageIcon("src/main/java/com/server/patolli/img/perfil2.png"),
        new ImageIcon("src/main/java/com/server/patolli/img/perfil3.png"),
        new ImageIcon("src/main/java/com/server/patolli/img/perfil4.png")
    };

    /**
     * Creates new form frmLobby
     */
    public frmLobby() {
        initComponents();
        setLocationRelativeTo(null);
        actualizarFoto(lblFoto1, 0, false);
        actualizarFoto(lblFoto2, 1, false);
        actualizarFoto(lblFoto3, 2, false);
        actualizarFoto(lblFoto4, 3, false);
        lblContador.setText(jugadores + "/4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLobby = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlJugador1 = new javax.swing.JPanel();
        tbtnRojo1 = new javax.swing.JToggleButton();
        tbtnVerde1 = new javax.swing.JToggleButton();
        tbtnAzul1 = new javax.swing.JToggleButton();
        tbtnAmarillo1 = new javax.swing.JToggleButton();
        btnArriba1 = new javax.swing.JButton();
        btnAbajo1 = new javax.swing.JButton();
        lblFoto1 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        tbtnListo1 = new javax.swing.JToggleButton();
        pnlJugador2 = new javax.swing.JPanel();
        tbtnRojo2 = new javax.swing.JToggleButton();
        tbtnVerde2 = new javax.swing.JToggleButton();
        tbtnAzul2 = new javax.swing.JToggleButton();
        tbtnAmarillo2 = new javax.swing.JToggleButton();
        btnArriba2 = new javax.swing.JButton();
        btnAbajo2 = new javax.swing.JButton();
        lblFoto2 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        tbtnListo2 = new javax.swing.JToggleButton();
        pnlJugador3 = new javax.swing.JPanel();
        tbtnRojo3 = new javax.swing.JToggleButton();
        tbtnVerde3 = new javax.swing.JToggleButton();
        tbtnAzul3 = new javax.swing.JToggleButton();
        tbtnAmarillo3 = new javax.swing.JToggleButton();
        btnArriba3 = new javax.swing.JButton();
        btnAbajo3 = new javax.swing.JButton();
        lblFoto3 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        tbtnListo3 = new javax.swing.JToggleButton();
        pnlJugador4 = new javax.swing.JPanel();
        tbtnRojo4 = new javax.swing.JToggleButton();
        tbtnVerde4 = new javax.swing.JToggleButton();
        tbtnAzul4 = new javax.swing.JToggleButton();
        tbtnAmarillo4 = new javax.swing.JToggleButton();
        btnArriba4 = new javax.swing.JButton();
        btnAbajo4 = new javax.swing.JButton();
        lblFoto4 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        tbtnListo4 = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLobby.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLobby.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLobby.setText("Lobby");

        tbtnRojo1.setBackground(new java.awt.Color(255, 0, 0));
        tbtnRojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRojo1ActionPerformed(evt);
            }
        });

        tbtnVerde1.setBackground(new java.awt.Color(0, 255, 0));
        tbtnVerde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVerde1ActionPerformed(evt);
            }
        });

        tbtnAzul1.setBackground(new java.awt.Color(0, 0, 255));
        tbtnAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAzul1ActionPerformed(evt);
            }
        });

        tbtnAmarillo1.setBackground(new java.awt.Color(255, 255, 0));
        tbtnAmarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAmarillo1ActionPerformed(evt);
            }
        });

        btnArriba1.setText("▲");
        btnArriba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriba1ActionPerformed(evt);
            }
        });

        btnAbajo1.setText("▼");
        btnAbajo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajo1ActionPerformed(evt);
            }
        });

        lblJugador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador1.setText("Jugador 1");

        tbtnListo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbtnListo1.setText("Listo");
        tbtnListo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnListo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador1Layout = new javax.swing.GroupLayout(pnlJugador1);
        pnlJugador1.setLayout(pnlJugador1Layout);
        pnlJugador1Layout.setHorizontalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador1Layout.createSequentialGroup()
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador1Layout.createSequentialGroup()
                        .addComponent(tbtnRojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador1Layout.createSequentialGroup()
                        .addComponent(tbtnAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbajo1)
                    .addComponent(btnArriba1))
                .addGap(0, 0, 0)
                .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnListo1)
                .addGap(0, 0, 0))
        );
        pnlJugador1Layout.setVerticalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador1Layout.createSequentialGroup()
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnListo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlJugador1Layout.createSequentialGroup()
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador1Layout.createSequentialGroup()
                        .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnRojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlJugador1Layout.createSequentialGroup()
                        .addComponent(btnArriba1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnAbajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbtnRojo2.setBackground(new java.awt.Color(255, 0, 0));
        tbtnRojo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRojo2ActionPerformed(evt);
            }
        });

        tbtnVerde2.setBackground(new java.awt.Color(0, 255, 0));
        tbtnVerde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVerde2ActionPerformed(evt);
            }
        });

        tbtnAzul2.setBackground(new java.awt.Color(0, 0, 255));
        tbtnAzul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAzul2ActionPerformed(evt);
            }
        });

        tbtnAmarillo2.setBackground(new java.awt.Color(255, 255, 0));
        tbtnAmarillo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAmarillo2ActionPerformed(evt);
            }
        });

        btnArriba2.setText("▲");
        btnArriba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriba2ActionPerformed(evt);
            }
        });

        btnAbajo2.setText("▼");
        btnAbajo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajo2ActionPerformed(evt);
            }
        });

        lblJugador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador2.setText("Jugador 2");

        tbtnListo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbtnListo2.setText("Listo");
        tbtnListo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnListo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador2Layout = new javax.swing.GroupLayout(pnlJugador2);
        pnlJugador2.setLayout(pnlJugador2Layout);
        pnlJugador2Layout.setHorizontalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador2Layout.createSequentialGroup()
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addComponent(tbtnRojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addComponent(tbtnAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnAmarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbajo2)
                    .addComponent(btnArriba2))
                .addGap(0, 0, 0)
                .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnListo2)
                .addGap(0, 0, 0))
        );
        pnlJugador2Layout.setVerticalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador2Layout.createSequentialGroup()
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnRojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnAmarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addComponent(btnArriba2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnAbajo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbtnListo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        tbtnRojo3.setBackground(new java.awt.Color(255, 0, 0));
        tbtnRojo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRojo3ActionPerformed(evt);
            }
        });

        tbtnVerde3.setBackground(new java.awt.Color(0, 255, 0));
        tbtnVerde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVerde3ActionPerformed(evt);
            }
        });

        tbtnAzul3.setBackground(new java.awt.Color(0, 0, 255));
        tbtnAzul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAzul3ActionPerformed(evt);
            }
        });

        tbtnAmarillo3.setBackground(new java.awt.Color(255, 255, 0));
        tbtnAmarillo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAmarillo3ActionPerformed(evt);
            }
        });

        btnArriba3.setText("▲");
        btnArriba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriba3ActionPerformed(evt);
            }
        });

        btnAbajo3.setText("▼");
        btnAbajo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajo3ActionPerformed(evt);
            }
        });

        lblJugador3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador3.setText("Jugador 3");

        tbtnListo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbtnListo3.setText("Listo");
        tbtnListo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnListo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador3Layout = new javax.swing.GroupLayout(pnlJugador3);
        pnlJugador3.setLayout(pnlJugador3Layout);
        pnlJugador3Layout.setHorizontalGroup(
            pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador3Layout.createSequentialGroup()
                .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador3Layout.createSequentialGroup()
                        .addComponent(tbtnRojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnVerde3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador3Layout.createSequentialGroup()
                        .addComponent(tbtnAzul3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnAmarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbajo3)
                    .addComponent(btnArriba3))
                .addGap(0, 0, 0)
                .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnListo3)
                .addGap(0, 0, 0))
        );
        pnlJugador3Layout.setVerticalGroup(
            pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador3Layout.createSequentialGroup()
                .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador3Layout.createSequentialGroup()
                        .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnRojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnVerde3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnAmarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnAzul3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlJugador3Layout.createSequentialGroup()
                        .addComponent(btnArriba3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnAbajo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbtnListo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        tbtnRojo4.setBackground(new java.awt.Color(255, 0, 0));
        tbtnRojo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRojo4ActionPerformed(evt);
            }
        });

        tbtnVerde4.setBackground(new java.awt.Color(0, 255, 0));
        tbtnVerde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVerde4ActionPerformed(evt);
            }
        });

        tbtnAzul4.setBackground(new java.awt.Color(0, 0, 255));
        tbtnAzul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAzul4ActionPerformed(evt);
            }
        });

        tbtnAmarillo4.setBackground(new java.awt.Color(255, 255, 0));
        tbtnAmarillo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAmarillo4ActionPerformed(evt);
            }
        });

        btnArriba4.setText("▲");
        btnArriba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriba4ActionPerformed(evt);
            }
        });

        btnAbajo4.setText("▼");
        btnAbajo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajo4ActionPerformed(evt);
            }
        });

        lblJugador4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador4.setText("Jugador 4");

        tbtnListo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbtnListo4.setText("Listo");
        tbtnListo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnListo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador4Layout = new javax.swing.GroupLayout(pnlJugador4);
        pnlJugador4.setLayout(pnlJugador4Layout);
        pnlJugador4Layout.setHorizontalGroup(
            pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador4Layout.createSequentialGroup()
                .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador4Layout.createSequentialGroup()
                        .addComponent(tbtnRojo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnVerde4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador4Layout.createSequentialGroup()
                        .addComponent(tbtnAzul4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tbtnAmarillo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbajo4)
                    .addComponent(btnArriba4))
                .addGap(0, 0, 0)
                .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnListo4)
                .addGap(0, 0, 0))
        );
        pnlJugador4Layout.setVerticalGroup(
            pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador4Layout.createSequentialGroup()
                .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador4Layout.createSequentialGroup()
                        .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnRojo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnVerde4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnAmarillo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnAzul4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlJugador4Layout.createSequentialGroup()
                        .addComponent(btnArriba4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnAbajo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbtnListo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblContador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblLobby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnRojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRojo1ActionPerformed
        actualizarEstadoBotones(tbtnRojo1, tbtnRojo2, tbtnRojo3, tbtnRojo4, Color.red);
    }//GEN-LAST:event_tbtnRojo1ActionPerformed

    private void tbtnRojo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRojo2ActionPerformed
        actualizarEstadoBotones(tbtnRojo2, tbtnRojo1, tbtnRojo3, tbtnRojo4, Color.red);
    }//GEN-LAST:event_tbtnRojo2ActionPerformed

    private void tbtnRojo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRojo3ActionPerformed
        actualizarEstadoBotones(tbtnRojo3, tbtnRojo1, tbtnRojo2, tbtnRojo4, Color.red);
    }//GEN-LAST:event_tbtnRojo3ActionPerformed

    private void tbtnRojo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRojo4ActionPerformed
        actualizarEstadoBotones(tbtnRojo4, tbtnRojo1, tbtnRojo2, tbtnRojo3, Color.red);
    }//GEN-LAST:event_tbtnRojo4ActionPerformed

    private void tbtnVerde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVerde1ActionPerformed
        actualizarEstadoBotones(tbtnVerde1, tbtnVerde2, tbtnVerde3, tbtnVerde4, Color.green);
    }//GEN-LAST:event_tbtnVerde1ActionPerformed

    private void tbtnVerde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVerde2ActionPerformed
        actualizarEstadoBotones(tbtnVerde2, tbtnVerde1, tbtnVerde3, tbtnVerde4, Color.green);
    }//GEN-LAST:event_tbtnVerde2ActionPerformed

    private void tbtnVerde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVerde3ActionPerformed
        actualizarEstadoBotones(tbtnVerde3, tbtnVerde1, tbtnVerde2, tbtnVerde4, Color.green);
    }//GEN-LAST:event_tbtnVerde3ActionPerformed

    private void tbtnVerde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVerde4ActionPerformed
        actualizarEstadoBotones(tbtnVerde4, tbtnVerde1, tbtnVerde2, tbtnVerde3, Color.green);
    }//GEN-LAST:event_tbtnVerde4ActionPerformed

    private void tbtnAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAzul1ActionPerformed
        actualizarEstadoBotones(tbtnAzul1, tbtnAzul2, tbtnAzul3, tbtnAzul4, Color.blue);
    }//GEN-LAST:event_tbtnAzul1ActionPerformed

    private void tbtnAzul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAzul2ActionPerformed
        actualizarEstadoBotones(tbtnAzul2, tbtnAzul1, tbtnAzul3, tbtnAzul4, Color.blue);
    }//GEN-LAST:event_tbtnAzul2ActionPerformed

    private void tbtnAzul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAzul3ActionPerformed
        actualizarEstadoBotones(tbtnAzul3, tbtnAzul1, tbtnAzul2, tbtnAzul4, Color.blue);
    }//GEN-LAST:event_tbtnAzul3ActionPerformed

    private void tbtnAzul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAzul4ActionPerformed
        actualizarEstadoBotones(tbtnAzul4, tbtnAzul1, tbtnAzul2, tbtnAzul3, Color.blue);
    }//GEN-LAST:event_tbtnAzul4ActionPerformed

    private void tbtnAmarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAmarillo1ActionPerformed
        actualizarEstadoBotones(tbtnAmarillo1, tbtnAmarillo2, tbtnAmarillo3, tbtnAmarillo4, Color.yellow);
    }//GEN-LAST:event_tbtnAmarillo1ActionPerformed

    private void tbtnAmarillo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAmarillo2ActionPerformed
        actualizarEstadoBotones(tbtnAmarillo2, tbtnAmarillo1, tbtnAmarillo3, tbtnAmarillo4, Color.yellow);
    }//GEN-LAST:event_tbtnAmarillo2ActionPerformed

    private void tbtnAmarillo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAmarillo3ActionPerformed
        actualizarEstadoBotones(tbtnAmarillo3, tbtnAmarillo1, tbtnAmarillo2, tbtnAmarillo4, Color.yellow);
    }//GEN-LAST:event_tbtnAmarillo3ActionPerformed

    private void tbtnAmarillo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAmarillo4ActionPerformed
        actualizarEstadoBotones(tbtnAmarillo4, tbtnAmarillo1, tbtnAmarillo2, tbtnAmarillo3, Color.yellow);
    }//GEN-LAST:event_tbtnAmarillo4ActionPerformed

    private void btnArriba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriba1ActionPerformed
        actualizarFoto(lblFoto1, 0, true);
    }//GEN-LAST:event_btnArriba1ActionPerformed

    private void btnAbajo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajo1ActionPerformed
        actualizarFoto(lblFoto1, 0, false);
    }//GEN-LAST:event_btnAbajo1ActionPerformed

    private void btnArriba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriba2ActionPerformed
        actualizarFoto(lblFoto2, 0, true);
    }//GEN-LAST:event_btnArriba2ActionPerformed

    private void btnAbajo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajo2ActionPerformed
        actualizarFoto(lblFoto2, 0, false);
    }//GEN-LAST:event_btnAbajo2ActionPerformed

    private void btnArriba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriba3ActionPerformed
        actualizarFoto(lblFoto3, 0, true);
    }//GEN-LAST:event_btnArriba3ActionPerformed

    private void btnAbajo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajo3ActionPerformed
        actualizarFoto(lblFoto3, 0, false);
    }//GEN-LAST:event_btnAbajo3ActionPerformed

    private void btnArriba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriba4ActionPerformed
        actualizarFoto(lblFoto4, 0, true);
    }//GEN-LAST:event_btnArriba4ActionPerformed

    private void btnAbajo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajo4ActionPerformed
        actualizarFoto(lblFoto4, 0, false);
    }//GEN-LAST:event_btnAbajo4ActionPerformed

    private void tbtnListo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnListo1ActionPerformed
        actualizarListo(tbtnListo1);
    }//GEN-LAST:event_tbtnListo1ActionPerformed

    private void tbtnListo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnListo2ActionPerformed
        actualizarListo(tbtnListo2);
    }//GEN-LAST:event_tbtnListo2ActionPerformed

    private void tbtnListo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnListo3ActionPerformed
        actualizarListo(tbtnListo3);
    }//GEN-LAST:event_tbtnListo3ActionPerformed

    private void tbtnListo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnListo4ActionPerformed
        actualizarListo(tbtnListo4);
    }//GEN-LAST:event_tbtnListo4ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        new frmTablero().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void actualizarEstadoBotones(JToggleButton botonPrincipal, JToggleButton boton1, JToggleButton boton2, JToggleButton boton3, Color color) {
        if (botonPrincipal.isSelected()) {
            boton1.setEnabled(false);
            boton1.setBackground(Color.gray);
            boton2.setEnabled(false);
            boton2.setBackground(Color.gray);
            boton3.setEnabled(false);
            boton3.setBackground(Color.gray);
        } else {
            boton1.setEnabled(true);
            boton1.setBackground(color);
            boton2.setEnabled(true);
            boton2.setBackground(color);
            boton3.setEnabled(true);
            boton3.setBackground(color);
        }
    }

    private void actualizarFoto(JLabel label, int perfil, boolean arriba) {
        if (arriba) {
            if (perfiles[perfil] > 0) {
                perfiles[perfil] = perfiles[perfil] - 1;
            } else {
                perfiles[perfil] = fotos.length - 1;
            }
        } else {
            if (perfiles[perfil] < fotos.length - 1) {
                perfiles[perfil] = perfiles[perfil] + 1;
            } else {
                perfiles[perfil] = 0;
            }
        }

        Image original = fotos[perfiles[perfil]].getImage();
        Image escalada = original.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);

        label.setIcon(new ImageIcon(escalada));
    }

    private void actualizarListo(JToggleButton boton) {
        if (boton.isSelected()) {
            jugadores++;
        } else {
            jugadores--;
        }
        lblContador.setText(jugadores + "/4");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbajo1;
    private javax.swing.JButton btnAbajo2;
    private javax.swing.JButton btnAbajo3;
    private javax.swing.JButton btnAbajo4;
    private javax.swing.JButton btnArriba1;
    private javax.swing.JButton btnArriba2;
    private javax.swing.JButton btnArriba3;
    private javax.swing.JButton btnArriba4;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblFoto4;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblLobby;
    private javax.swing.JPanel pnlJugador1;
    private javax.swing.JPanel pnlJugador2;
    private javax.swing.JPanel pnlJugador3;
    private javax.swing.JPanel pnlJugador4;
    private javax.swing.JToggleButton tbtnAmarillo1;
    private javax.swing.JToggleButton tbtnAmarillo2;
    private javax.swing.JToggleButton tbtnAmarillo3;
    private javax.swing.JToggleButton tbtnAmarillo4;
    private javax.swing.JToggleButton tbtnAzul1;
    private javax.swing.JToggleButton tbtnAzul2;
    private javax.swing.JToggleButton tbtnAzul3;
    private javax.swing.JToggleButton tbtnAzul4;
    private javax.swing.JToggleButton tbtnListo1;
    private javax.swing.JToggleButton tbtnListo2;
    private javax.swing.JToggleButton tbtnListo3;
    private javax.swing.JToggleButton tbtnListo4;
    private javax.swing.JToggleButton tbtnRojo1;
    private javax.swing.JToggleButton tbtnRojo2;
    private javax.swing.JToggleButton tbtnRojo3;
    private javax.swing.JToggleButton tbtnRojo4;
    private javax.swing.JToggleButton tbtnVerde1;
    private javax.swing.JToggleButton tbtnVerde2;
    private javax.swing.JToggleButton tbtnVerde3;
    private javax.swing.JToggleButton tbtnVerde4;
    // End of variables declaration//GEN-END:variables
}
